// Mocks generated by Mockito 5.0.16 from annotations
// in quoter/test/quoter_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;
import 'dart:math' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:quoter/src/models/models.dart' as _i4;
import 'package:quoter/src/repositories/repositories.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [QuoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuoteRepository extends _i1.Mock implements _i2.QuoteRepository {
  MockQuoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Quote>> getQuotes() =>
      (super.noSuchMethod(Invocation.method(#getQuotes, []),
              returnValue: Future<List<_i4.Quote>>.value(<_i4.Quote>[]))
          as _i3.Future<List<_i4.Quote>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Random].
///
/// See the documentation for Mockito's code generation for more information.
class MockRandom extends _i1.Mock implements _i5.Random {
  MockRandom() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int nextInt(int? max) =>
      (super.noSuchMethod(Invocation.method(#nextInt, [max]), returnValue: 0)
          as int);
  @override
  double nextDouble() =>
      (super.noSuchMethod(Invocation.method(#nextDouble, []), returnValue: 0.0)
          as double);
  @override
  bool nextBool() =>
      (super.noSuchMethod(Invocation.method(#nextBool, []), returnValue: false)
          as bool);
  @override
  String toString() => super.toString();
}
