name: quoter
description: A flutter pacakge that returns random quote.
version: 0.0.1
homepage: https://github.com/muhammadidrees/quoter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  mockito: ^5.0.16

flutter:

